#' Boruta-Based Feature Selection for Spectral Predictors
#'
#' Applies the Boruta algorithm to select informative spectral predictors by comparing
#' variable importance scores against randomized shadow features. Intended for use after
#' spectral preprocessing (e.g., SNV + derivatives) and before downstream modeling.
#'
#' @param recipe A `recipes::recipe()` object.
#' @param ... Selector functions choosing the spectral columns Boruta runs on,
#'   e.g. `dplyr::matches("^spec[0-9]+$")` — the names
#'   `step_transform_spectra()` gives its output. Select by name pattern rather
#'   than `all_predictors()`: a covariate promoted to the predictor role is
#'   inside `all_predictors()` by the time this step preps, and would then be
#'   clustered and shadow-tested as if it were a wavenumber. A selector
#'   matching nothing aborts at `prep()`.
#' @param outcome Character. Name of the outcome variable to use for model fitting.
#' @param role Character. Role for retained variables. Default is `"predictor"`.
#' @param trained Logical. Required by `recipes`; indicates if the step has been prepped.
#' @param skip Logical. Should this step be skipped during `bake()`? Default is `FALSE`.
#' @param id Character. Unique identifier for the step. Auto-generated by default.
#'
#' @return A `step_select_boruta` object that can be added to a recipe.
#'
#' @details
#' This step uses the Boruta feature selection algorithm, which runs a random forest model
#' comparing each original predictor to shuffled "shadow" variables. Variables consistently
#' more important than the best shadow are retained. The algorithm is run at `prep()` time.
#'
#' For best results, this step should be applied *after* spectral preprocessing (e.g. SNV,
#' derivatives) and *before* PCA or model fitting. It may be computationally expensive
#' for large spectral datasets.
#'
#' Boruta runs on at most 50 cluster representatives of the selected columns
#' (correlation clustering), for at most 25 runs of a 250-tree ranger forest.
#' Its `mtry` is `round(2 * sqrt(n))` for `n` representatives (at least 5, at
#' most `n - 1`), and each run clamps it to the columns that run is given,
#' which shrink as Boruta rejects attributes. Attributes Boruta leaves
#' tentative are kept with the confirmed ones, and each kept representative
#' brings its whole cluster.
#'
#' When Boruta confirms nothing, the step warns with class
#' `horizons_boruta_warning`: if it rejected every attribute, the step keeps
#' all the variance-filtered columns; otherwise it keeps the tentative ones.
#' When Boruta itself fails, `prep()` aborts with class `horizons_boruta_error`.
#' There is no fallback selector, so `evaluate()` and `fit()` record the
#' configuration as failed.
#'
#' The trained step records what Boruta did in its `boruta` element: the
#' confirmed, tentative and rejected counts, each attribute's `decision`, the
#' `runs`, `max_runs` and `num_trees`, the `mtry` ceiling and the `mtry` of
#' each run (`mtry_by_run`), and `retained_all`. `print()` shows the counts.
#'
#' @export

## -----------------------------------------------------------------------------
## Step 1: User-facing step constructor
## -----------------------------------------------------------------------------

#' @export
step_select_boruta <- function(recipe,
                               ...,
                               outcome,
                               role    = "predictor",
                               trained = FALSE,
                               skip    = FALSE,
                               id      = recipes::rand_id("select_boruta")) {

  terms <- rlang::enquos(...)

  recipes::add_step(recipe,
                    step_select_boruta_new(terms         = terms,
                                           columns       = NULL,
                                           outcome       = outcome,
                                           role          = role,
                                           trained       = trained,
                                           selected_vars = NULL,
                                           boruta        = NULL,
                                           skip          = skip,
                                           id            = id))
}

## -----------------------------------------------------------------------------
## Step 2: Constructor
## -----------------------------------------------------------------------------

## Follows recipes' own contract: `terms` holds the selector quosures and
## survives prep, so a trained recipe can be re-prepped (`fresh = TRUE`);
## `columns` holds the names prep resolved them to, and is what bake reads.
## `boruta` is prep's record of what Boruta did (see prep()); bake never
## reads it, and a step trained before it existed has none.

#' @keywords internal
#' @noRd
step_select_boruta_new <- function(terms,
                                   columns,
                                   outcome,
                                   role,
                                   trained,
                                   selected_vars,
                                   boruta = NULL,
                                   skip,
                                   id) {

  out <- list(terms          = terms,
              columns        = columns,
              outcome        = outcome,
              role           = role,
              trained        = trained,
              selected_vars  = selected_vars,
              boruta         = boruta,
              skip           = skip,
              id             = id )

  class(out) <- c("step_select_boruta", "step")
  return(out)

}

## -----------------------------------------------------------------------------
## Step 3: prep() method
## -----------------------------------------------------------------------------

#' @export
prep.step_select_boruta <- function(x, training, info = NULL, ...) {

  ## ---------------------------------------------------------------------------
  ## Stage 1: Resolve spectral column names
  ## ---------------------------------------------------------------------------

  selectors <- step_selectors(x, "step_select_boruta")
  col_names <- recipes::recipes_eval_select(selectors, training, info)

  check_selection_columns(col_names, "step_select_boruta")

  if (!is.character(x$outcome) || length(x$outcome) != 1) {
    cli::cli_abort("The {.arg outcome} must be a single character string.")
  }

  if (!x$outcome %in% names(training)) {
    cli::cli_abort("Outcome column {.val {x$outcome}} not found in training data.")
  }

  outcome_vec  <- training[[x$outcome]]
  spectra_mat  <- as.matrix(training[, col_names, drop = FALSE])

  ## ---------------------------------------------------------------------------
  ## Stage 2: Variance filtering and clustering
  ## ---------------------------------------------------------------------------

  # Remove near-constant features before clustering
  variance_check <- apply(spectra_mat, 2, var, na.rm = TRUE)
  keep_cols <- variance_check > 1e-10

  if(sum(keep_cols) < ncol(spectra_mat)) {
    cli::cli_alert_info("Filtering {ncol(spectra_mat) - sum(keep_cols)} near-constant features before clustering")
    spectra_mat <- spectra_mat[, keep_cols, drop = FALSE]
    col_names_filtered <- col_names[keep_cols]
  } else {
    col_names_filtered <- col_names
  }

  # Use more aggressive clustering for spectral data (k=50 instead of 150)
  cluster_spectral_predictors(spectra_mat,
                              k      = min(50, ncol(spectra_mat)),
                              method = "correlation") -> cluster_result

  reduced_mat   <- cluster_result$reduced_mat
  cluster_map   <- cluster_result$cluster_map
  cluster_vars  <- cluster_result$selected_vars

  ## ---------------------------------------------------------------------------
  ## Stage 3: Run Boruta
  ## ---------------------------------------------------------------------------

  ## The random forest settings live here and reach ranger through the
  ## importance source below, which is the only place Boruta hands them on
  ## to. Boruta() passes its own `...` to a custom `getImp`, so settings given
  ## to Boruta() as `ntree` or `mtry` would do nothing unless the importance
  ## source read them.

  max_runs     <- 25L
  num_trees    <- 250L
  n_features   <- ncol(reduced_mat)
  optimal_mtry <- min(max(5, round(sqrt(n_features) * 2)), n_features - 1)

  ## -------------------------------------------------------------------------
  ## Importance source: ranger, mtry clamped per call
  ## -------------------------------------------------------------------------

  ### Boruta calls this once per run with the attributes not yet rejected plus
  ### their shadows, a matrix that narrows as attributes are rejected. A fixed
  ### mtry outgrows it once fewer than mtry / 2 attributes remain, ranger
  ### aborts, and Boruta with it (#75), so each call clamps to the columns it
  ### is given. The mtry of every run is kept for the trained record.

  mtry_by_run <- integer(0)

  ranger_importance <- function(x, y, ...) {

    mtry <- as.integer(max(1L, min(optimal_mtry, ncol(x))))

    mtry_by_run <<- c(mtry_by_run, mtry)

    rf <- ranger::ranger(x           = x,
                         y           = y,
                         num.trees   = num_trees,
                         mtry        = mtry,
                         importance  = "impurity",
                         num.threads = 1,
                         verbose     = FALSE)

    rf$variable.importance

  }

  ## -------------------------------------------------------------------------
  ## A failed Boruta run fails the step
  ## -------------------------------------------------------------------------

  ### There is no fallback selector. The step used to fall back to the 50
  ### columns most correlated with the outcome, so a config labelled "boruta"
  ### ran a correlation filter with nothing in the results saying so. An
  ### error here fails the config in evaluate() and fit().

  boruta_fit <- tryCatch(Boruta::Boruta(x           = reduced_mat,
                                        y           = outcome_vec,
                                        doTrace     = 0,
                                        maxRuns     = max_runs,
                                        holdHistory = FALSE,
                                        getImp      = ranger_importance),
                         error = function(e) e)

  if (inherits(boruta_fit, "error")) {

    boruta_error <- conditionMessage(boruta_fit)

    cli::cli_abort(c(
      "Boruta feature selection failed: {boruta_error}",
      "i" = "Boruta ran on {n_features} cluster representative{?s} of {length(col_names_filtered)} wavenumber{?s}, with ranger mtry at most {optimal_mtry}.",
      "i" = "{.fn step_select_boruta} has no fallback selector, so the step fails rather than select by another method."
    ), class = "horizons_boruta_error")

  }

  decision <- boruta_fit$finalDecision

  boruta_record <- list(n_attributes = n_features,
                        n_confirmed  = sum(decision == "Confirmed"),
                        n_tentative  = sum(decision == "Tentative"),
                        n_rejected   = sum(decision == "Rejected"),
                        decision     = decision,
                        runs         = length(mtry_by_run),
                        max_runs     = max_runs,
                        num_trees    = num_trees,
                        mtry         = as.integer(optimal_mtry),
                        mtry_by_run  = mtry_by_run,
                        retained_all = FALSE)

  ## ---------------------------------------------------------------------------
  ## Stage 4: Map back to original wavenumbers
  ## ---------------------------------------------------------------------------

  ## Tentative attributes are kept with the confirmed ones: maxRuns is capped
  ## at 25 for speed, so Boruta often stops before it decides them.
  ##
  ## Boruta confirming nothing is a result, not a failure, and the step says
  ## so rather than pass it off as a selection. Two cases:
  ##
  ##   - Every attribute rejected: nothing is selected, so the step keeps every
  ##     variance-filtered wavenumber, as the other selection steps keep all
  ##     their columns when they select nothing.
  ##   - None confirmed, some tentative: the selection is the tentative
  ##     attributes, none of which Boruta showed to beat the shadows.
  ##
  ## Both warn, and the trained record carries the counts either way.

  kept_cluster_vars <- Boruta::getSelectedAttributes(boruta_fit, withTentative = TRUE)

  if (length(kept_cluster_vars) == 0) {

    cli::cli_warn(c(
      "Boruta rejected all {n_features} attribute{?s} it tested, so {.fn step_select_boruta} selected nothing.",
      "i" = "Retaining all {length(col_names_filtered)} variance-filtered wavenumber{?s}; the model sees an unselected spectrum."
    ), class = "horizons_boruta_warning")

    kept_wavenumbers           <- col_names_filtered
    boruta_record$retained_all <- TRUE

  } else {

    kept_wavenumbers <- unique(unlist(cluster_map[kept_cluster_vars]))

    if (boruta_record$n_confirmed == 0) {

      cli::cli_warn(c(
        "Boruta confirmed none of the {n_features} attribute{?s} it tested in {boruta_record$runs} run{?s}.",
        "i" = "The selection is the {boruta_record$n_tentative} attribute{?s} it left tentative ({length(kept_wavenumbers)} wavenumber{?s}), none shown to beat the shadow features."
      ), class = "horizons_boruta_warning")

    }

  }

  ## ---------------------------------------------------------------------------
  ## Stage 5: Return trained step
  ## ---------------------------------------------------------------------------

  step_select_boruta_new(terms          = selectors,
                         columns        = col_names,
                         outcome        = x$outcome,
                         role           = x$role,
                         trained        = TRUE,
                         selected_vars  = kept_wavenumbers,
                         boruta         = boruta_record,
                         skip           = x$skip,
                         id             = x$id)
}


## -----------------------------------------------------------------------------
## Step 4: bake() method
## -----------------------------------------------------------------------------

#' @export
bake.step_select_boruta <- function(object, new_data, ...) {

  if (is.null(object$selected_vars)) {
    cli::cli_abort("This step has not been trained yet. Please call `prep()` first.")
  }

  if (!all(object$selected_vars %in% names(new_data))) {
    cli::cli_abort("Some selected wavenumbers are missing in new_data.")
  }

  ## Retain: selected spectral vars + all non-spectral columns
  keep_cols <- c(object$selected_vars,
                 setdiff(names(new_data),
                         object$columns))

  dplyr::select(new_data, dplyr::all_of(keep_cols))

}

## -----------------------------------------------------------------------------
## Step 5: print() method
## -----------------------------------------------------------------------------

#' @export
print.step_select_boruta <- function(x,
                                     width = max(20, options()$width - 30),
                                     ...) {

  ## glue() trims a trailing newline, so each line ends with its own.
  cat("Boruta-based spectral feature selection step\n")
  cat(glue::glue("\u2022 Outcome column: {x$outcome}"), "\n", sep = "")

  if (x$trained) {

    cat(glue::glue("\u2022 {length(x$selected_vars)} wavenumbers retained after Boruta"), "\n", sep = "")

    ## A step trained before the record existed has none to show.
    b <- x$boruta

    if (!is.null(b)) {

      cat(glue::glue("\u2022 Boruta: {b$n_confirmed} confirmed, {b$n_tentative} tentative, ",
                     "{b$n_rejected} rejected of {b$n_attributes} cluster representatives ",
                     "in {b$runs} runs"), "\n", sep = "")

      if (isTRUE(b$retained_all)) {
        cat("\u2022 Nothing selected, so every variance-filtered wavenumber is retained\n")
      }

    }

  } else {
    cat("\u2022 Step not yet trained\n")
  }

  invisible(x)
}


